create table `countries` (
	id INT,
	title VARCHAR(50),
	iso VARCHAR(50)
);
insert into `countries` (id, title, iso) values (1, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (2, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (3, 'United States', 'US');
insert into `countries` (id, title, iso) values (4, 'United States', 'US');
insert into `countries` (id, title, iso) values (5, 'United States', 'US');
insert into `countries` (id, title, iso) values (6, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (7, 'United States', 'US');
insert into `countries` (id, title, iso) values (8, 'United States', 'US');
insert into `countries` (id, title, iso) values (9, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (10, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (11, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (12, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (13, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (14, 'United States', 'US');
insert into `countries` (id, title, iso) values (15, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (16, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (17, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (18, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (19, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (20, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (21, 'United States', 'US');
insert into `countries` (id, title, iso) values (22, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (23, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (24, 'United States', 'US');
insert into `countries` (id, title, iso) values (25, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (26, 'United States', 'US');
insert into `countries` (id, title, iso) values (27, 'United States', 'US');
insert into `countries` (id, title, iso) values (28, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (29, 'United States', 'US');
insert into `countries` (id, title, iso) values (30, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (31, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (32, 'United States', 'US');
insert into `countries` (id, title, iso) values (33, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (34, 'United States', 'US');
insert into `countries` (id, title, iso) values (35, 'United States', 'US');
insert into `countries` (id, title, iso) values (36, 'United States', 'US');
insert into `countries` (id, title, iso) values (37, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (38, 'United States', 'US');
insert into `countries` (id, title, iso) values (39, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (40, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (41, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (42, 'United States', 'US');
insert into `countries` (id, title, iso) values (43, 'United States', 'US');
insert into `countries` (id, title, iso) values (44, 'United States', 'US');
insert into `countries` (id, title, iso) values (45, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (46, 'United States', 'US');
insert into `countries` (id, title, iso) values (47, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (48, 'United States', 'US');
insert into `countries` (id, title, iso) values (49, 'United States', 'US');
insert into `countries` (id, title, iso) values (50, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (51, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (52, 'United States', 'US');
insert into `countries` (id, title, iso) values (53, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (54, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (55, 'United States', 'US');
insert into `countries` (id, title, iso) values (56, 'Canada', 'CA');
insert into `countries` (id, title, iso) values (57, 'United States', 'US');
insert into `countries` (id, title, iso) values (58, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (59, 'Mexico', 'MX');
insert into `countries` (id, title, iso) values (60, 'Canada', 'CA');
