create table `states` (
	id INT,
	title VARCHAR(50),
	code VARCHAR(50)
);
insert into `states` (id, title, code) values (1, 'It', 'PE');
insert into `states` (id, title, code) values (2, 'Trippledex', 'US');
insert into `states` (id, title, code) values (3, 'Trippledex', 'UA');
insert into `states` (id, title, code) values (4, 'Kanlam', 'RU');
insert into `states` (id, title, code) values (5, 'Bytecard', 'KR');
insert into `states` (id, title, code) values (6, 'Span', 'US');
insert into `states` (id, title, code) values (7, 'Stim', 'PK');
insert into `states` (id, title, code) values (8, 'Otcom', 'BR');
insert into `states` (id, title, code) values (9, 'Zontrax', 'CN');
insert into `states` (id, title, code) values (10, 'Biodex', 'CI');
insert into `states` (id, title, code) values (11, 'Kanlam', 'CD');
insert into `states` (id, title, code) values (12, 'Ronstring', 'BR');
insert into `states` (id, title, code) values (13, 'Aerified', 'BR');
insert into `states` (id, title, code) values (14, 'Kanlam', 'BF');
insert into `states` (id, title, code) values (15, 'Tin', 'MX');
insert into `states` (id, title, code) values (16, 'Zontrax', 'UA');
insert into `states` (id, title, code) values (17, 'Zamit', 'AU');
insert into `states` (id, title, code) values (18, 'Vagram', 'BR');
insert into `states` (id, title, code) values (19, 'Sub-Ex', 'TZ');
insert into `states` (id, title, code) values (20, 'Bitchip', 'NO');
insert into `states` (id, title, code) values (21, 'Treeflex', 'CA');
insert into `states` (id, title, code) values (22, 'Regrant', 'KE');
insert into `states` (id, title, code) values (23, 'Domainer', 'GB');
insert into `states` (id, title, code) values (24, 'Stringtough', 'US');
insert into `states` (id, title, code) values (25, 'Toughjoyfax', 'US');
insert into `states` (id, title, code) values (26, 'Zoolab', 'BF');
insert into `states` (id, title, code) values (27, 'Tin', 'EG');
insert into `states` (id, title, code) values (28, 'Sonsing', 'EC');
insert into `states` (id, title, code) values (29, 'Voltsillam', 'PG');
insert into `states` (id, title, code) values (30, 'Alpha', 'AU');
insert into `states` (id, title, code) values (31, 'Greenlam', 'LY');
insert into `states` (id, title, code) values (32, 'Y-Solowarm', 'US');
insert into `states` (id, title, code) values (33, 'Opela', 'PA');
insert into `states` (id, title, code) values (34, 'Sonair', 'ID');
insert into `states` (id, title, code) values (35, 'Cardify', 'SI');
insert into `states` (id, title, code) values (36, 'Fintone', 'GB');
insert into `states` (id, title, code) values (37, 'Fixflex', 'PL');
insert into `states` (id, title, code) values (38, 'Treeflex', 'PG');
insert into `states` (id, title, code) values (39, 'Pannier', 'US');
insert into `states` (id, title, code) values (40, 'Keylex', 'CN');
insert into `states` (id, title, code) values (41, 'Transcof', 'CZ');
insert into `states` (id, title, code) values (42, 'Bitchip', 'US');
insert into `states` (id, title, code) values (43, 'Gembucket', 'PF');
insert into `states` (id, title, code) values (44, 'Andalax', 'AR');
insert into `states` (id, title, code) values (45, 'Y-find', 'BS');
insert into `states` (id, title, code) values (46, 'Stim', 'CN');
insert into `states` (id, title, code) values (47, 'Cardguard', 'IN');
insert into `states` (id, title, code) values (48, 'Sonsing', 'DE');
insert into `states` (id, title, code) values (49, 'Matsoft', 'IN');
insert into `states` (id, title, code) values (50, 'Tin', 'CD');
insert into `states` (id, title, code) values (51, 'Stronghold', 'RU');
insert into `states` (id, title, code) values (52, 'Sonsing', 'PG');
insert into `states` (id, title, code) values (53, 'Bigtax', 'US');
insert into `states` (id, title, code) values (54, 'Ronstring', 'CN');
insert into `states` (id, title, code) values (55, 'Daltfresh', 'PG');
insert into `states` (id, title, code) values (56, 'Stronghold', 'CF');
insert into `states` (id, title, code) values (57, 'Mat Lam Tam', 'TC');
insert into `states` (id, title, code) values (58, 'Fixflex', 'DE');
insert into `states` (id, title, code) values (59, 'Zontrax', 'AU');
insert into `states` (id, title, code) values (60, 'Treeflex', 'SO');
